version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: unless-stopped
    depends_on:
      - intelligence

  intelligence:
    build:
      context: ./intelligence
    ports:
      - "8000:8000"
    restart: unless-stopped
